version: '3.8'

services:
  webrtc-signaling:
    build: .
    container_name: webrtc-signaling
    restart: unless-stopped


    expose:
      - "4000" 
    environment:
      - NODE_ENV=production
      - PORT=4000

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" 
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - webrtc-signaling

volumes:
  caddy_data:
  caddy_config: